[Swings]  # where is store my own constants

# magica       = used in long buy price dips
# mediumout = used in short sell
# shortsight   = used in short sell

#these 4 can now be in a percentage!
# based upon long moving average

Magica         = 0.11      
MediumOut  = 0.1   
ShortSight    = 0.2   
HighShot     = 0.01

# if you dont want that set below to false!
UsePercentage = true  


# downhill = short after price drop since highest
# highshot = short after price jump 2 new candles
# bullseye = secure profit since bought
# daystop = max los stops trade till next day

# those are still fixed numbers
DownHill = 280 
BullsEye = 500    
DayStop = 600     


[ForcastTrend] 
# forcast trend tulip indicator
Short =  6 
Medium = 17
Long = 100   #nan

[PeriodAverage] 
# moving averages
Short = 6 
Medium = 25
Long = 100

[VolumePeriodAverage]
# volume moving averages  
Short  = 6    #not used
Medium = 30  
Long   = 100  #not used

[RSISafety] 
# go short when above percentage
# wait buy  if RSI> rsiWait
# using x candles
RSIShort = 0.8
RSIWait  = 0.7 
RSIcandles  = 6