# SMA INDICATOR
SMA_long = 1000
SMA_short = 50
SMA_Timeframe = 7

#Fast Check Percentage
fastPercentCheck = 5
fastMaFast = 3
fastMaDiff = 1

#Stoploss Percentage
stopLoss = 5
#Enable Trailing Stop
trailStop = 1

# RSI BULL / BEAR
BULL_RSI = 10
BULL_RSI_high = 80
BULL_RSI_low = 60
BULL_RSI_Timeframe = 7


BEAR_RSI = 15
BEAR_RSI_high = 50
BEAR_RSI_low = 20
BEAR_RSI_Timeframe = 7


# MODIFY RSI (depending on ADX)
BULL_MOD_high = 5
BULL_MOD_low = -5
BEAR_MOD_high = 15
BEAR_MOD_low = -5

# ADX
ADX = 3
ADX_high = 70
ADX_low = 50

ADX_Timeframe = 7
