# 기준 봉 크기
candle_duration = 30 #단위는 min
#매수 조건
#case1
[buy]
  [buy.condition]
    [buy.condition.case1]
      prev_candle_count = 3  #(이전 {3}개 봉
      up_candle = true
      prev_volume_surge_ratio = 3 # 이전 봉들의 평균거래량 * {x} 배
      prev_price_surge_ratio = 0.001 #1-3. 이전 {3}개봉의 평균가격(각 봉의(open+close)/2의 평균)보다 {0.1%}이상 상승)
    [buy.condition.case2]
      prev_candle_count = 3  #(이전 {3}개 봉
      up_candle = true
      prev_volume_surge_ratio2 = 5 # 이전 봉들의 평균거래량 * {x} 배
      prev_max_num_candle = 10 #2-3. 이전 {10}개봉의 최고가격

#매도 조건
[sell]
  [sell.condition]
    loss_ratio = 0.02 # 손절가율 2% 미만이면 손절
    [sell.condition.case1]
      prev_candle_count = 3  #(이전 {3}개 봉
      prev_volume_surge_ratio = 3 # 이전 봉들의 평균거래량 * {x} 배
    [sell.condition.range1]
      a = 0.03
      b = 0.05
      c = 0.09 # 수익율 기준,현재 10% 수익이지만 10%*50% 미만 수익율, 즉 5%미만이면 매도
    [sell.condition.range2]
      a = 0.05
      b = 0.2
      c = 0.25
    [sell.condition.range3]
      a = 0.2
      b = 10
      c = 0.15
