# SMA Trends
SMA_long = 500
SMA_short = 20

# BULL
BULL_RSI = 10
BULL_RSI_high = 90
BULL_RSI_low = 40

# BEAR
BEAR_RSI = 15
BEAR_RSI_high = 50
BEAR_RSI_low = 20

# BULL/BEAR is defined by the longer SMA trends
# if SHORT over LONG = BULL
# if SHORT under LONG = BEAR
