# SMA INDICATOR
SMA_long = 180
SMA_short = 55
SMA_Timeframe = 10

# RSI BULL / BEAR
BULL_RSI = 9
BULL_RSI_high = 85
BULL_RSI_low = 60
BULL_RSI_Timeframe = 10

BEAR_RSI = 12.5
BEAR_RSI_high = 60
BEAR_RSI_low = 25
BEAR_RSI_Timeframe = 10

# MODIFY RSI (depending on ADX)
BULL_MOD_high = 5
BULL_MOD_low = -5
BEAR_MOD_high = 5
BEAR_MOD_low = -5

# ADX
ADX = 10
ADX_high = 50
ADX_low = 40
ADX_Timeframe = 10

# Stop Loss & Gain
Stop_Loss_Percent = 10
Stop_Gain_Percent = 30

#Minimum Short SPREAD Percentage (won't sell if less than x%)
Min_Loss_Percent = 0.5
Min_Gain_Percent = 1.5